version: "3.7"
services:
  api:
    image: elsiedev/testhng:apitest
    ports:
      - 8000:8000
    # container_name: api
    # networks:
    #   - client-api-net


  frontend:
    image: elsiedev/testhng:front
    # container_name: frontend
    # networks:
    #   - client-api-net
    ports:
      - 3000:3000

# networks:
#   client-api-net:
#     driver: bridge
