version: "3"
services:
  api:
    image: elsiedev/testhng:api
    expose:
      - 8080
    container_name: api
    networks:
      - client-api-net

  frontend:
    image: elsiedev/testhng:front
    container_name: frontend
    networks:
      - client-api-net
    ports:
      - "3000:3000"

networks:
  client-api-net:
    driver: bridge